### ISSUE TITLE
Handle count before commands

### ISSUE THREAD

**Issue by ecogest** [declancm/cinnamon.nvim#1]
Hello,

Thanks for this great plugin !

Sill, how can we use a count before a command ? (ex: `42G` goes right at the bottom even if there are more than 42 lines, where G is mapped this way: `keymap('n', 'G', "<Cmd>lua Cinnamon.Scroll('G', 0, 0, 3)<CR>", opts)`)

Regards.

**Comment by declancm** [comment]
Thank you for liking it!!
The third argument for the function enables using a count so 'G' should be mapped to:
```lua
keymap('n', 'G', "<Cmd>lua Cinnamon.Scroll('G', 0, 1, 3)<CR>", opts)
```
I updated this for the README and the 'extra keymaps' which will be generated to fix this issue.
Could you please try updating the plugin and let me know if you have still have any issues :).
Thanks again!
