### ISSUE TITLE
[Bug] Hiding the cursor does not restore it when the scroll is completed

### ISSUE THREAD

**Issue by akinsho** [declancm/cinnamon.nvim#11]
Hi,

I've noticed when using `hide_cursor = true` that my cursor is hidden but, it is never put back when the scrolling is completed. I faced a similar issue using `neoscroll` a while back which the author eventually fix so, cribbing that solution might be applicable here.

**Comment by declancm** [comment]
Hi!

I'll definitely look into what neoscroll did for their cursor hiding. Do you know if you have this issue randomly or does it occur immediately when you try to scroll for the first time?

**Comment by akinsho** [comment]
@declancm it happens immediately I try to scroll which is expected, i.e. the cursor disappears, but then it never comes back when I stop scrolling

**Comment by akinsho** [comment]
@declancm here's the issue for neoscroll https://github.com/karb94/neoscroll.nvim/issues/42
here's the PR which fixed it https://github.com/karb94/neoscroll.nvim/commit/54879c6957ee5e833924064ff7fc17c144502ae9

**Comment by declancm** [comment]
I think the guicursor was not getting restored properly so hopefully this commit fixes your issue 😬

**Comment by akinsho** [comment]
Still seems to persist on the latest commit, unfortunately.

**Comment by declancm** [comment]
Hopefully this commit has fixed your issue. By using the custom highlight group, it should be very similar to what neoscroll does

**Comment by akinsho** [comment]
@declancm sorry meant to say I enabled it this morning and my cursor reappears correctly now 👍🏾
