### ISSUE TITLE
Setting to toggle the smooth scrolling

### ISSUE THREAD

**Issue by WilliamHsieh** [declancm/cinnamon.nvim#17]
Is there a setting / function to toggle the smooth scrolling? I would like to toggle the smooth scrolling on my need. Thank's!

**Comment by kvngvikram** [comment]
I need the same thing.
I generally open large data files in vim. To quickly inspect I just keep Ctrl-F pressed, which is basically many Ctrl-F together. 
Now with cinnamon, the scrolling happens slowly, which is fine but until all the Ctrl-Fs are done, I am locked out of vim.
So a toggle would be very helpful for me

**Comment by declancm** [comment]
Hi! I added a config option to disable the function. This can be used to toggle the plugin:

```lua
lua require('cinnamon.config').disabled = not require('cinnamon.config').disabled
```

Hopefully this works for you both :)
