### ISSUE TITLE
Show number of results

### ISSUE THREAD

**Issue by CRAG666** [declancm/cinnamon.nvim#2]
First of all this plugin is amazing really love this. Now the problem is that I would like the plugin when scrolling with n, N in the search results to print the number of results and what number of results I am in, for example 17/36

**Comment by declancm** [comment]
Thank you so much! I'm glad you like it!
Could you try adding this to your init.lua and let me know if that is what you were wanting:
```lua
vim.opt.shortmess = vim.opt.shortmess - 'S'
```
or for init.vim:
```vim
set shortmess-=S
```
It shows the result number in the bottom right for the search commands
(I only just found out about this today and its life changing haha)

**Comment by CRAG666** [comment]
Unfortunately I can't see the number of results, I guess it's because of the default mapping that silences the commands. I leave you my configuration.

```lua
        require("cinnamon").setup {
          default_keymaps = true, -- Enable default keymaps.
          extra_keymaps = true, -- Enable extra keymaps.
          extended_keymaps = true, -- Enable extended keymaps.
          centered = true, -- Keep cursor centered in window when using window scrolling (arg2):
        }
```

**Comment by CRAG666** [comment]
@declancm This doesn't work either
```lua
        local opts = { noremap = true, silent = false }
        local keymap = vim.api.nvim_set_keymap
        keymap("n", "n", "<Cmd>lua Cinnamon.Scroll('n')<CR>", opts)
        keymap("n", "N", "<Cmd>lua Cinnamon.Scroll('N')<CR>", opts)

```
That is, if the number of results is printed but it does not change position since what is printed is <position>/<results> then it prints 17/34 but when I press n or N the 17 does not change

**Comment by declancm** [comment]
@CRAG666 I tried using that config and it works for me so I checked out your dotfiles. I think the issue was that lazyredraw was set to true . When I tried setting it to true in my own config, I got the same issue that you are talking about. I am just adding a commit now which will set lazyredraw to false just for scroll so it should hopefully work now if you update :)
