### ISSUE TITLE
Goes up one extra line and then comes back when moving upwards

### ISSUE THREAD

**Issue by utilyre** [declancm/cinnamon.nvim#21]
Hi, thanks for such great plugin!

## Config

```lua
{
  default_keymaps = true,
  extra_keymaps = true,
  extended_keymaps = true,
  always_scroll = true,
  scroll_limit = 64,
}
```

## Reproduction

https://user-images.githubusercontent.com/91974155/209425143-a44a7e9e-7c1e-4ed7-82a0-e4524d8b333e.mp4

**Comment by declancm** [comment]
I'm not able to view the video but if you have wrap enabled then it should be fixed with the latest commits
