### ISSUE TITLE
 Feature request: add 'keepjumps' argument to Scroll function

### ISSUE THREAD

**Issue by plasmik010** [declancm/cinnamon.nvim#22]
I don't want my jump list to collect all the 'n' motions, so this is what i had in Vim: 
nnoremap <silent> n :<C-u>execute "keepjumps norm! " . v:count1 . "nzz"<CR>
nnoremap <silent> N :<C-u>execute "keepjumps norm! " . v:count1 . "Nzz"<CR>

Would be nice to control which motions in this plugin are or are not passed to the jumplist.

**Comment by declancm** [comment]
I'll definitely add that!

**Comment by declancm** [comment]
Now possible by using a command-line command or lua function
