### ISSUE TITLE
Holding down a movement key with scrolling crashes neovim

### ISSUE THREAD

**Issue by sungkang** [declancm/cinnamon.nvim#23]
it seems to happen with any call to Scroll(). I would visit a long file and hold down the key (ctrl d/u) in my case. Sometimes I would reach the end of the file, but I could get it crashing every time.

below are my plugin setup options using lazy.nvim:

  {
    'declancm/cinnamon.nvim',
    opts = {
      default_delay = 1,
      extra_keymaps = true,
    },
  },

**Comment by declancm** [comment]
Hi! Sorry for taking so long to get to this! Do you get any error messages? What version of Neovim are you running? I've tried reproducing with your config and haven't had it crash yet

**Comment by svranesevic** [comment]
I've been able to reproduce this issue with Neovim HEAD @ `1ee905a63`.  
There is no any error message(s), nvim simply exists/closes, and checking `$1` / `$status (fish)` shows that exit code is 141.

**Comment by declancm** [comment]
Should be fixed on the latest.
