### ISSUE TITLE
[Docs] Add example

### ISSUE THREAD

**Issue by TheElegantCoding** [declancm/cinnamon.nvim#24]
Please add an example in the readme so people can see how it looks after installint and configure this plugin

**Comment by declancm** [comment]
I have an example configuration as well as a packer installation example. Are you looking for a GIF or something that shows the plugin being used? Or are you wanting more installation examples? Thanks!

**Comment by TheElegantCoding** [comment]
I am talking about the gif in the readme

**Comment by declancm** [comment]
Added
