### ISSUE TITLE
statusline/lualine flashes with cmdheight=0

### ISSUE THREAD

**Issue by diocletiann** [declancm/cinnamon.nvim#27]
Thanks for the awesome plugin! One small issue, I use `cmdheight=0` and when pressing C-d/u, statusline and lualine flashes which is impossible to not see. Hoping there's a solution, thanks.

**Comment by declancm** [comment]
Thanks for using the plugin! Hopefully that commit fixes your issue

**Comment by declancm** [comment]
Feel free to reopen this issue if you're still having issues!
