### ISSUE TITLE
`gj` and `gk` functionality

### ISSUE THREAD

**Issue by simonmandlik** [declancm/cinnamon.nvim#31]
Hi, is it possible to get smooth scroll also for `gj` and `gk`?

The following MWE works:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        'declancm/cinnamon.nvim',
        opts = {}
    }
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.keymap.set('n', 'j', [[<Cmd>lua Scroll("j", 1, 1)<CR>]])
vim.keymap.set('n', 'k', [[<Cmd>lua Scroll("k", 1, 1)<CR>]])
vim.keymap.set('n', 'gj', [[<Cmd>lua Scroll("gj", 1, 1)<CR>]])
vim.keymap.set('n', 'gk', [[<Cmd>lua Scroll("gk", 1, 1)<CR>]])
```

However, while `j` and `k` work fine, `gj` and `gk` are very slow on larger lines (or lines with inlay hints)

**Comment by declancm** [comment]
Added them to the 'no scroll' list so it should be a lot faster when used without a count :).
Currently the gj and gk won't work smoothly when finishing on wrapped text, I need to fix that before added those keymaps to the 'extended keymaps'. I'll open another issue for that

**Comment by declancm** [comment]
See #32

**Comment by declancm** [comment]
The fix was easier than I thought, I've added 'gj' and 'gk' to the extended keymaps

**Comment by simonmandlik** [comment]
Great!

Just FYI, I have successfully setup `g0`, `g^` and `g$` variants. These are not set up with `extra_keymaps`, but work for me anyway
