### ISSUE TITLE
Not selecting to the end of the line by pressing $ in visual block mode

### ISSUE THREAD

**Issue by ilias777** [declancm/cinnamon.nvim#34]
Hi.

First I have to say thank you for your plugin. 

I saw an issue last time I wanted to select a code block in visual block mode without the prepend whitespace. If in cinnamon the `extra_keymaps` are set to `true`, it's not possible to select to end of the line by pressing `$`. With `extra_keymaps` set to `false`, the text are selected as expected.

To understand what i mean, see the two screenrecordings:

**Without extra keymaps:**

https://github.com/declancm/cinnamon.nvim/assets/39212564/f2114baf-426d-4427-8043-2dbb290eeabf

**With extra keymaps:**

https://github.com/declancm/cinnamon.nvim/assets/39212564/ab3c517d-d56f-4c06-ad18-f05d1aab50a8

As you can see, it's not possible to select the text up to the end of the line if `extra_keymaps` are enabled. I hope you can fix this.
Thank you again.

**Comment by declancm** [comment]
Should be fixed! :)

**Comment by ilias777** [comment]
That was quick! It's fixed now. Thank you 👍🏻
