### ISSUE TITLE
Cannot center after rewrite

### ISSUE THREAD

**Issue by NicolasGB** [declancm/cinnamon.nvim#37]
Hi, thanks for the plugin it's really awesome!

I was migrating my config to the new one, and i love my commands centered, i've read the docs and replicated the half page up/down, but i can't make it work.

this is my current config:
```lua
{
    "declancm/cinnamon.nvim",
    config = function()
      require("cinnamon").setup {
        keymaps = { extra = true }, -- Enable the 'extra' keymaps
      }
      local scroll = require("cinnamon").scroll

      -- Centered scrolling:
      vim.keymap.set("n", "<C-U>", scroll("<C-U>zz", {}))
      vim.keymap.set("n", "<C-D>", scroll "<C-D>zz")
    end,
  }
```

But i get this error:

![image](https://github.com/declancm/cinnamon.nvim/assets/17547539/086d3d50-5d70-4d38-83f8-5e134d21cd27)

Tried wrapping the function in function () ... end, the error goes away but the scrolling isn't centered.

If i can bring any additional information let me know :)

**Comment by NicolasGB** [comment]
Okay wrapping it in a function such as:
```lua
      local cinnamon = require "cinnamon"
      -- Centered scrolling:
      vim.keymap.set("n", "<C-u>", function()
        cinnamon.scroll "<C-u>zz"
      end)
      vim.keymap.set({ "n", "x" }, "<C-d>", function()
        cinnamon.scroll "<C-d>zz"
      end)
```
Does seem to work!
I might have tried it too fast previously

**Comment by declancm** [comment]
Great! Your last code snippet also works for me. I should add a better config example especially for people who had used the centering option previously

**Comment by declancm** [comment]
Oh actually yes the examples need to be wrapped in a function oops
