### ISSUE TITLE
dont use `/plugin` for setup function

### ISSUE THREAD

**Issue by max397574** [declancm/cinnamon.nvim#4]
calling the setup function in `/plugin` seems not really useful to me.
Users should call the setup function.

Normally this wouldn't be a big deal but in this case it creates keymaps before I call the setup function where I disable default keymaps.

**Comment by declancm** [comment]
Originally I was checking if a user had called the setup function in their config and only calling it if this doesn't occur, but I guess this wouldn't work when calling setup from outside config or some other special cases. I removed the plugin folder so hopefully it should be working now!
