### ISSUE TITLE
Weird behaviour if indent style is tab

### ISSUE THREAD

**Issue by ilias777** [declancm/cinnamon.nvim#44]
Recently I opened a file with indent tabs instead of spaces and I saw this:

https://github.com/declancm/cinnamon.nvim/assets/39212564/bdb093c3-19ac-4d50-a4ea-5ba1e851ba70

This issue is when `extra keymaps` and `basic keymaps` is set to `true`. 

My cinnamon config:

```lua
{
    'declancm/cinnamon.nvim',
    enabled = true,
    event = { 'WinNew' },
    opts = {
        keymaps = {
            basic = true,
            extra = true,
        },
        options = {
            delay = 5,
            max_delta = {
                column = 100,
            },
        },
    },
},
```

**Comment by ilias777** [comment]
Sorry for the noice. I changed the event flag to `WinNew` and the problem doesn't exist any more. 😬

**Comment by declancm** [comment]
Do you still get this issue when you set max_delta.column to nil and set the version to 1.0.1?

**Comment by ilias777** [comment]
I tested it now. 
I changed the `max_delta.column` to `nil` and I have the latest version (1.0.1) installed.
The issue doesn't exist any more.

But if I change the `event` flag to something else, like `event = { 'BufReadPre', 'BufNewFile' }`, only one jump to the first non-blank character of the line appears.
If `event = { 'WinNew' }` is set, it works normal as expected.

**With other `event = { 'BufReadPre', 'BufNewFile' }`:**

https://github.com/declancm/cinnamon.nvim/assets/39212564/ffb9dca3-ff4b-4116-ae94-bb66b2a3701b

**With event `event = { 'WinNew' }`:**

https://github.com/declancm/cinnamon.nvim/assets/39212564/e5268314-868a-44b9-b409-6365030423f9

Really good work  🙂👍🏻
