### ISSUE TITLE
[Bug] Setting basic or extra keymaps to true generates error and stops all scrolling in neovim

### ISSUE THREAD

**Issue by zoomido** [declancm/cinnamon.nvim#49]
In the latest version, enabling the basic or extra keymaps and then trying to use any scrolling keybind generates below error and then scrolling stops working in neovim. Everything used to work a few versions back when I had the old configuration names like extra_keymaps.

> E5108: Error executing lua: ...al/share/nvim/lazy/cinnamon.nvim/lua/cinnamon/scroll.lua:131: attempt to call field 'keycode' (a nil value)            
> stack traceback:                                                                                                                                      
>         ...al/share/nvim/lazy/cinnamon.nvim/lua/cinnamon/scroll.lua:131: in function 'execute_command'                                                
>         ...al/share/nvim/lazy/cinnamon.nvim/lua/cinnamon/scroll.lua:32: in function 'scroll'                                                          
>         ...ocal/share/nvim/lazy/cinnamon.nvim/lua/cinnamon/init.lua:17: in function <...ocal/share/nvim/lazy/cinnamon.nvim/lua/cinnamon/init.lua:17>

> {
>         -- Smooth scrolling
>         'declancm/cinnamon.nvim',
>         opts = {
>             keymaps = {
>                 -- Enable the provided 'basic' keymaps
>                 basic = true,
>                 -- Enable the provided 'extra' keymaps
>                 extra = false,
>             },
>         },
>     },
>

**Comment by declancm** [comment]
Your version of Neovim is missing vim.keycode. I'll submit a fix to use the older nvim_replace_termcodes
