### ISSUE TITLE
is there a way to  temporarily disable animation?

### ISSUE THREAD

**Issue by KevinNitroG** [declancm/cinnamon.nvim#54]
Hi, I want to ask if there is a way to temporarily disable animation. I saw a way to do that in [`echasnovski/mini.animate`](https://github.com/echasnovski/mini.animate/blob/320fb35460238c436407cd779f63abad98e84870/doc/mini-animate.txt#L95C1-L102C1) to disable animation globally or for a buffer, and it is used in [LazyVim](https://www.lazyvim.org/configuration/general#auto-commands).

```lua
vim.filetype.add({
  pattern = {
    [".*"] = {
      function(path, buf)
        return vim.bo[buf]
            and vim.bo[buf].filetype ~= "bigfile"
            and path
            and vim.fn.getfsize(path) > vim.g.bigfile_size
            and "bigfile"
          or nil
      end,
    },
  },
})

vim.api.nvim_create_autocmd({ "FileType" }, {
  group = augroup("bigfile"),
  pattern = "bigfile",
  callback = function(ev)
    vim.b.minianimate_disable = true
    vim.schedule(function()
      vim.bo[ev.buf].syntax = vim.filetype.match({ buf = ev.buf }) or ""
    end)
  end,
})
```

It would be nice to temporarily disable animation for big files. And I wonder do we have some kinds like that in our plugin?

Thank you anyway!

**Comment by declancm** [comment]
No sorry, but I'll definitely add that ASAP!

**Comment by declancm** [comment]
You can disable the animation for large movements by setting the 'max_delta' config option

To disable scrolling for movements larger than 200 lines (or columns):

```lua
require("cinnamon").setup({
    options = {
         max_delta = {
             line = 200,
             column = 200,
         },
    },
})
```

**Comment by KevinNitroG** [comment]
> You can disable the animation for large movements by setting the 'max_delta' config option
> 
> To disable scrolling for movements larger than 200 lines (or columns):
> 
> ```lua
> require("cinnamon").setup({
>     options = {
>          max_delta = {
>              line = 200,
>              column = 200,
>          },
>     },
> })
> ```

Huhm I think it's not quite enough for me. Because with just a large file, a small movement like `<C-d>` still makes a noticeable delay and lag. 🙁

**Comment by declancm** [comment]
Hopefully this fixes your lag with large files! I'll still add an option for disabling cinnamon per buffer either way

**Comment by KevinNitroG** [comment]
> Hopefully this fixes your lag with large files! I'll still add an option for disabling cinnamon per buffer either way

Thank you! It's work great (:
