### ISSUE TITLE
`<C-u>`/`<C-d>` doesn't work after 857095c

### ISSUE THREAD

**Issue by fitrh** [declancm/cinnamon.nvim#6]
69c8ace8644dcd8e599b3c9e68fe2fb24c1df15d works fine, the issue appears after 857095c03d00e9b4c6869c6e93c182f9d99066c8

Tell me if you need something for reproduction

**Comment by declancm** [comment]
From that commit the default keymaps no longer override keymaps that already exist. Could you please try executing `:map <C-U>` to check if a keymap is being set somewhere else?

To just override the other keymaps you can add to add to your config:

```lua
vim.keymap.set({ 'n', 'x' }, '<C-u>', "<Cmd>lua Scroll('<C-u>', 1, 1)<CR>")
vim.keymap.set({ 'n', 'x' }, '<C-d>', "<Cmd>lua Scroll('<C-d>', 1, 1)<CR>")
```

Could you please let me know how you go :)

**Comment by fitrh** [comment]
> Could you please try executing :map <C-U> to check if a keymap is being set somewhere else?

69c8ace8644dcd8e599b3c9e68fe2fb24c1df15d give me that those keys mapped to the `Scroll` function in `Normal` and `Visual` map-mode (`n`, `x`)

but 857095c03d00e9b4c6869c6e93c182f9d99066c8 map `Scroll` function only for `Visual` map-mode (`x`)

**Comment by fitrh** [comment]
Manually setting keymap for `<C-u>`/`<C-d>` fixed the problem, but why should I do it if I never override the keymap ?

**Comment by declancm** [comment]
I think the keymaps might be getting set by another plugin? If `:nmap <C-U>` doesn't show anything then I'm not sure why cinnamon is detecting a pre-existing keymap. I'm now adding an option to override all existing keymaps if you update the plugin :)

```lua
require("cinnamon").setup({
  override_keymaps = true,
})
```

**Comment by fitrh** [comment]
As far as I'm aware, there is no plugin that overrides the key, and if it does, `:map` will show you where the keys has been mapped.

Thanks for the latest commit, it fixed the issue
