### ISSUE TITLE
`gg` & `G` is not using default_delay

### ISSUE THREAD

**Issue by gnituy18** [declancm/cinnamon.nvim#7]
I found this in init.lua
```
utils.create_keymap({ 'n', 'x' }, 'gg', "<Cmd>lua Scroll('gg', 0, 0, 5)<CR>")
utils.create_keymap({ 'n', 'x' }, 'G', "<Cmd>lua Scroll('G', 0, 1, 5)<CR>")
```
Is it possible for gg and G to use default delay like others?

**Comment by declancm** [comment]
I'll change that now :). I had gg and G set to a faster speed than the default since its usually a much bigger movement than the others. I'll change it to match the others just for consistency though

**Comment by gnituy18** [comment]
Thanks! I actually set all my delays to 1 to scroll faster but still have the smooth scrolling experience.
