### ISSUE TITLE
[Feature request] hide cursor on scroll

### ISSUE THREAD

**Issue by leohasa** [declancm/cinnamon.nvim#9]
Nice plugin :+1:

It would be perfect if you could add the functionality for the cursor to hide when scrolling. This would make the scrolling experience more enjoyable.

**Comment by declancm** [comment]
I'll definitely try and implement this asap! :)

**Comment by declancm** [comment]
Hi @L2AsHdz !

I just tried implementing this in the latest commit: baaaf0043165c9c5f01ebdec70ec4aaf64f909c8. Just make sure you have termguicolors enabled in your nvim config and set the hide_cursor option.

```lua
require('cinnamon').setup {
  hide_cursor = true,
}
```

I hope this works for you, please let me know how it goes!

**Comment by leohasa** [comment]
Great! Thanks for taking the time to implement it.
I'll try it out and let you know how it goes. :+1:

**Comment by leohasa** [comment]
Works perfect, thanks again!

**Comment by declancm** [comment]
That's great to hear :) . It was no problem!
